#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

#define CONFIGURATION_H_VERSION 020008
#define PRUSA_SKR_CONFIGURATION_VERSION "2020-12-1"

//===========================================================================
//============================== Printer Name ===============================
//===========================================================================

// "Turbo" moniker is not added because it exceeds the status area's 20 chararcter
// limit due to "Printer Name" + " Ready."

#ifdef PRUSA_SKR_CUSTOM_NAME
  #define CUSTOM_MACHINE_NAME PRUSA_SKR_CUSTOM_NAME
#elif PRUSA_SKR_FRAME_TYPE == 1 || PRUSA_SKR_FRAME_TYPE == 2
  #define CUSTOM_MACHINE_NAME "SKR Bear"
#elif PRUSA_SKR_FRAME_TYPE == 3
  #define CUSTOM_MACHINE_NAME "SKR Caribou"
#endif

//===========================================================================
//=========================== Printer/Frame Type ============================
//===========================================================================

// Prusa Bear frame is enabled by default.

/**
 * Options:  1: Bear       (210mm Z)
 *           2: Tall Bear  (310mm Z)
 *           3: Caribou    (320mm Z)
 */
#ifndef PRUSA_SKR_FRAME_TYPE
  #error "PRUSA_SKR_FRAME_TYPE not found."
#elif PRUSA_SKR_FRAME_TYPE < 1 || PRUSA_SKR_FRAME_TYPE > 3
  #error "PRUSA_SKR_FRAME_TYPE must be between 1 and 3"
#elif PRUSA_SKR_FRAME_TYPE == 1 // Bear
  #define Z_MAX_POS 210
#elif PRUSA_SKR_FRAME_TYPE == 2 // Tall Bear
  #define Z_MAX_POS 310
#elif PRUSA_SKR_FRAME_TYPE == 3 // Caribou
  #define Z_MAX_POS 320
#endif

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

// SKR 1.4 is enabled by default.

/**
 * Options:  1: BigTreeTech SKR 1.4        (LPC1768)
 *           2: BigTreeTech SKR 1.4 Turbo  (LPC1769)
 */
#ifndef PRUSA_SKR_MOTHERBOARD
  #error "PRUSA_SKR_MOTHERBOARD not found."
#elif PRUSA_SKR_MOTHERBOARD < 1 || PRUSA_SKR_MOTHERBOARD > 2
  #error "PRUSA_SKR_MOTHERBOARD must be between 1 and 2"
#elif PRUSA_SKR_MOTHERBOARD == 1
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4
#elif PRUSA_SKR_MOTHERBOARD == 2
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
#endif

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

/**
 * Extruder Stepper
 *
 * Stock 1.8° extruder stepper is enabled by default.
 *
 * Options:  1: Stock 1.8°
 *           2: Bondtech/Motech 1.8° pancake
 *           3: LDO 0.9° pancake
 *           4: LDO planetary
 */
#ifndef PRUSA_SKR_E_STEPPER
  #error "PRUSA_SKR_E_STEPPER not found."
#elif PRUSA_SKR_E_STEPPER < 1 || PRUSA_SKR_E_STEPPER > 4
  #error "PRUSA_SKR_E_STEPPER must be between 1 and 4"
#elif (PRUSA_SKR_E_STEPPER == 1) && (PRUSA_SKR_EXTRUDER == 3 || PRUSA_SKR_EXTRUDER == 4)
  #error "Stock 1.8° stepper on a BMG extruder is not supported."
#elif (PRUSA_SKR_E_STEPPER == 2 || PRUSA_SKR_E_STEPPER == 3) && (PRUSA_SKR_EXTRUDER == 1 || PRUSA_SKR_EXTRUDER == 2)
  #error "Pancake stepper on a Bear extruder is not supported."
#elif (PRUSA_SKR_E_STEPPER == 4) && (PRUSA_SKR_EXTRUDER == 3 || PRUSA_SKR_EXTRUDER == 4)
  #error "Planetary stepper on a BMG extruder is not supported."
#elif PRUSA_SKR_E_STEPPER == 1 // Stock 1.8°
  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  280
  #define E0_CURRENT                         550
  #define E0_MICROSTEPS                       32
#elif PRUSA_SKR_E_STEPPER == 2 // Bondtech/Motech 1.8° pancake
  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  830
  #define E0_CURRENT                         550
  #define E0_MICROSTEPS                       32
#elif PRUSA_SKR_E_STEPPER == 3 // LDO 0.9° pancake
  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  830
  #define E0_CURRENT                         800
  #define E0_MICROSTEPS                       16
#elif PRUSA_SKR_E_STEPPER == 4 // LDO planetary
  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  980
  #define E0_CURRENT                         650
  #define E0_MICROSTEPS                       32
#elif PRUSA_SKR_E_STEPPER == 5 // TriangleLab 3:1 stepper
  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  420
  #define E0_CURRENT                         550
  #define E0_MICROSTEPS                       16
#endif

/**
 * X/Y Steppers
 *
 * Stock 1.8° X/Y steppers are enabled by default.
 *
 * Options:  1: Stock 1.8° X/Y
 *           2: LDO 0.9° X/Y
 *           3: Moons 0.9° X/Y
 */
#ifndef PRUSA_SKR_XY_STEPPER
  #error "PRUSA_SKR_XY_STEPPER not found."
#elif PRUSA_SKR_XY_STEPPER < 1 || PRUSA_SKR_XY_STEPPER > 3
  #error "PRUSA_SKR_XY_STEPPER must be between 1 and 3"
#elif PRUSA_SKR_XY_STEPPER == 1 // Stock 1.8° X/Y
  #define DEFAULT_AXIS_STEPS_PER_UNIT  { 100, 100, 400, (PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT) }
  #define INVERT_X_DIR  false
  #define INVERT_Y_DIR   true
  #define X_CURRENT       500
  #define X_CURRENT_HOME  200
  #define Y_CURRENT       600
  #define Y_CURRENT_HOME  250
  #ifndef PRUSA_SKR_X_STALL_SENSITIVITY
    #define X_STALL_SENSITIVITY  90
  #endif
  #ifndef PRUSA_SKR_Y_STALL_SENSITIVITY
    #define Y_STALL_SENSITIVITY  100
  #endif
#elif PRUSA_SKR_XY_STEPPER == 2 || PRUSA_SKR_XY_STEPPER == 3 // LDO or Moons 0.9° X/Y
  #define DEFAULT_AXIS_STEPS_PER_UNIT   { 200, 200, 400, (PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT) }

  #if PRUSA_SKR_XY_STEPPER == 2 // LDO 0.9° X/Y
    #define INVERT_X_DIR   true
    #define INVERT_Y_DIR  false
    #define X_CURRENT       900
    #define X_CURRENT_HOME  300
    #define Y_CURRENT      1000
    #define Y_CURRENT_HOME  400
    #ifndef PRUSA_SKR_X_STALL_SENSITIVITY
      #define X_STALL_SENSITIVITY  81
    #endif
    #ifndef PRUSA_SKR_Y_STALL_SENSITIVITY
      #define Y_STALL_SENSITIVITY  85
    #endif
  #elif PRUSA_SKR_XY_STEPPER == 3 // Moons 0.9° X/Y
    #define INVERT_X_DIR  false
    #define INVERT_Y_DIR   true
    #define X_CURRENT       650
    #define X_CURRENT_HOME  225
    #define Y_CURRENT       750
    #define Y_CURRENT_HOME  200
    #ifndef PRUSA_SKR_X_STALL_SENSITIVITY
      #define X_STALL_SENSITIVITY  140
    #endif
    #ifndef PRUSA_SKR_Y_STALL_SENSITIVITY
      #define Y_STALL_SENSITIVITY  132
    #endif
  #endif
#endif

//===========================================================================
//================================= Hotend ==================================
//===========================================================================

/**
 * Extruder
 *
 * Bear Extruder is enabled by default.
 *
 * Options:   1: Bear extruder w/ PINDA V2 or SuperPINDA
 *            2: Bear extruder w/ integrated BLTouch mount by Vertigo 235 https://www.prusaprinters.org/prints/6606
 *            3: Bondtech BMG extruder w/ PINDA V2 or SuperPINDA https://www.bondtech.se/en/product/prusa-i3-mk3s-extruder-upgrade/
 *            4: Bondtech BMG extruder w/ BLTouch mount by Vertigo 235 https://www.prusaprinters.org/prints/6623
 */
#ifndef PRUSA_SKR_EXTRUDER
  #error "PRUSA_SKR_EXTRUDER not found."
#elif PRUSA_SKR_EXTRUDER < 1 || PRUSA_SKR_EXTRUDER > 4
  #error "PRUSA_SKR_EXTRUDER must be between 1 and 4"
#elif PRUSA_SKR_EXTRUDER == 2 || PRUSA_SKR_EXTRUDER == 4 // Bear or Bondtech BMG Extruder with BLTouch
  #define BLTOUCH
  #define TEMP_SENSOR_PROBE           0
  #define PROBING_MARGIN              5
  #define Z_CLEARANCE_DEPLOY_PROBE    5
  #define Z_CLEARANCE_BETWEEN_PROBES  3
  #define Z_CLEARANCE_MULTI_PROBE     3
  //#define Z_STEPPER_ALIGN_XY { { 10, 105 }, { 220, 105 } }    // Use default locations?

  #ifdef PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
    #define NOZZLE_TO_PROBE_OFFSET PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
  #elif PRUSA_SKR_EXTRUDER == 4 // Bondtech BMG Extruder w/ BLTouch mount
    #define NOZZLE_TO_PROBE_OFFSET { -24.3, -34.1, 0 } // Pulled from https://www.thingiverse.com/thing:3864666/comments#comment-2882122
  #elif PRUSA_SKR_EXTRUDER == 2 // Bear Extruder w/ integrated BLTouch mount
    #define NOZZLE_TO_PROBE_OFFSET { 26.71, 2.298, 0 } // Pulled from https://www.thingiverse.com/thing:3251530/comments#comment-2915938
  #endif

#elif PRUSA_SKR_EXTRUDER == 1 || PRUSA_SKR_EXTRUDER == 3 // Bear Extruder or Bondtech BMG with PINDA V2/SuperPINDA

  #ifndef PRUSA_SKR_PINDA_PROBE
    #error "PRUSA_SKR_PINDA_PROBE not found."
  #elif PRUSA_SKR_PINDA_PROBE == 1 // PINDA V2
    #define TEMP_SENSOR_PROBE 1
  #elif PRUSA_SKR_PINDA_PROBE == 2 // SuperPINDA
    #define TEMP_SENSOR_PROBE 0
  #endif

  #define FIX_MOUNTED_PROBE

  #ifdef PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
    #define NOZZLE_TO_PROBE_OFFSET PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
  #else
    #define NOZZLE_TO_PROBE_OFFSET { 23, 5, 0 }
  #endif

  #define PROBING_MARGIN 10
  #define Z_CLEARANCE_DEPLOY_PROBE    0
  #define Z_CLEARANCE_BETWEEN_PROBES  2
  #define Z_CLEARANCE_MULTI_PROBE     2
  #define PROBING_HEATERS_OFF
  #define Z_STEPPER_ALIGN_XY { { 40, 90 }, { 230,  90 } }
#endif

//===========================================================================
//=============================== Thermistor ================================
//===========================================================================

/**
 * Thermistor
 *
 * Stock E3D Semitec 104NT thermistor is enabled by default.
 *
 * Options:  1: E3D Semitec 104NT thermistor
 *           2: Slice Engineering's 450°C High Temperature thermistor
 *              !WARNING! If you plan to print above 295°C, you will need to upgrade from the stock V6 aluminum block or it will soften and/or melt!
 */
#ifndef PRUSA_SKR_THERMISTOR
  #error "PRUSA_SKR_THERMISTOR not found."
#elif PRUSA_SKR_THERMISTOR < 1 || PRUSA_SKR_THERMISTOR > 2
  #error "PRUSA_SKR_THERMISTOR must be between 1 and 2"
#elif PRUSA_SKR_THERMISTOR == 1
  #define TEMP_SENSOR_0  5
  #define HEATER_0_MAXTEMP (295 + 15)
#elif PRUSA_SKR_THERMISTOR == 2
  #define TEMP_SENSOR_0 67
  #define HEATER_0_MAXTEMP (450 + 15)
#endif

//===========================================================================
//============================= Filament Runout =============================
//===========================================================================

// If filament runout is throwing false alarms, uncomment & increase this value.
// This is NOT the same as FILAMENT_RUNOUT_DISTANCE_MM. See FILAMENT_RUNOUT_DISTANCE_MM in Configuration.h for more info.

//#define FILAMENT_RUNOUT_THRESHOLD 5

// Should this setting be exposed to users?

//===========================================================================
//============================== Bed Leveling ===============================
//===========================================================================

// Bilinear is enabled by default.

/**
 * Options:  1: Bilinear
 *           2: Unified Bed Leveling
 */
#ifndef PRUSA_SKR_BED_LEVELING
  #error "PRUSA_SKR_BED_LEVELING not found."
#elif PRUSA_SKR_BED_LEVELING < 1 || PRUSA_SKR_BED_LEVELING > 2
  #error "PRUSA_SKR_BED_LEVELING must be between 1 and 2"
#elif PRUSA_SKR_BED_LEVELING == 1
  #define AUTO_BED_LEVELING_BILINEAR
  #define HOTEND_IDLE_TIMEOUT_SEC (5*60)
#elif PRUSA_SKR_BED_LEVELING == 2
  #define AUTO_BED_LEVELING_UBL
  #define HOTEND_IDLE_TIMEOUT_SEC (15*60) // Longer timeout due to increased probe time
#endif

//===========================================================================
//================================= Display =================================
//===========================================================================

//Stock/OLED RepRapDiscount smart controller is enabled by default.

/**
 * Options:  1: Stock/OLED RepRapDiscount smart controller
 *           2: BigTreeTech Dual Mode TFT (TFT35/TFT50/TFT70,etc.)
 */
#ifndef PRUSA_SKR_DISPLAY
  #error "PRUSA_SKR_DISPLAY not found."
#elif PRUSA_SKR_DISPLAY < 1 || PRUSA_SKR_DISPLAY > 2
  #error "PRUSA_SKR_DISPLAY must be between 1 and 2"
#elif PRUSA_SKR_DISPLAY == 1
  #define REPRAP_DISCOUNT_SMART_CONTROLLER
  #define LCD_INFO_SCREEN_STYLE 1
#elif PRUSA_SKR_DISPLAY == 2
  #define MESH_EDIT_GFX_OVERLAY
  #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
  #define BOOT_MARLIN_LOGO_ANIMATED
  #define BABYSTEP_ZPROBE_GFX_OVERLAY
#endif

//===========================================================================
//================================ NeoPixels ================================
//===========================================================================

// NeoPixels are disabled by default.

#if ENABLED(PRUSA_SKR_NEOPIXELS)
  #define NEOPIXEL_LED
  #define LED_CONTROL_MENU

  #ifndef PRUSA_SKR_NEOPIXEL_TYPE
    #define NEOPIXEL_TYPE   NEO_GRB
  #endif
  #ifndef PRUSA_SKR_NEOPIXEL_PIXELS
    #define NEOPIXEL_PIXELS 17
  #endif
  #ifndef PRUSA_SKR_NEOPIXEL_BRIGHTNESS
    #define NEOPIXEL_BRIGHTNESS 255
  #endif
#endif
